### ISSUE TITLE
[УЛУЧШЕНИЕ] Доработка нормализации для EventId 4742

### ISSUE THREAD

**Issue by driverenok** [Security-Experts-Community/open-xp-rules#414]
### Существует ли уже issue или обсуждение с похожим предложением?

- [X] Подтверждаю, что предлагаемые улучшения ещё не были описаны

### Тип контента

Нормализация

### Что хотелось бы улучшить?

Из существующей нормализции события EventId 4742 не понятно какие именно атрибуты учетной записи были изменены. Было бы не плохо добавить поле reason, в котором собрать список измененных атрибутов.

### Почему Ваше предложение лучше, чем существующее решение?

Это пригодилось бы при написании детекта Zerologon, в котором важно мониторить факт изменения **пароля учетной записи**.

**Comment by aw350m33d** [comment]
Отличная идея! 
А есть возможность сделать PR c необходимыми правками?

**Comment by driverenok** [comment]
да, я сделаю, в reason кладем?

**Comment by aw350m33d** [comment]
Да, давай пока в reason. Посмотрим на получившиеся правки, а название поля поменять потом минутное дело)
